/*
"avatar": "https://s3-qcloud.meiqia.com/pics.meiqia.bucket/avatars/20181009/dd395676b1812e591c6c208f5ef99f10.png",
    "cellphone": null,
    "deleted_at": null,
    "enterprise_id": 5869,
    "id": 9422,
    "is_online": true,
    "nickname": "\u6d4b\u8bd5111",
    "privilege": "admin",
    "privilege_range": "all",
    "public_cellphone": "15678908988",
    "public_email": "23455678@qq.com",
    "qq": "456789",
    "read_feature_id": 19,
    "realname": "\u7ba1\u7406\u5458666",
    "signature": "\u5927\u5bb6\u597d",
    "status": "on_duty",
    "telephone": "34567890",
    "token": "767762e6969a6c77b426b7c7356cef3f",
    "weixin": "8901234"
 */
CREATE TABLE `agent` (
  `id` CHAR(20) PRIMARY KEY,
  `ent_id` CHAR(20) NOT NULL COMMENT '租户id',
  `group_id` CHAR(20) NOT NULL,
  `role_id` CHAR(20) NOT NULL,
  `avatar` VARCHAR(250) NOT NULL DEFAULT '',
  `username` VARCHAR(255) NOT NULL COMMENT '用户名',
  `real_name` VARCHAR(100) NOT NULL DEFAULT '',
  `nick_name` VARCHAR(100) NOT NULL DEFAULT '',
  `hashed_password` CHAR(60) NOT NULL COMMENT 'hashed密码',
  `job_number` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '工号',
  `serve_limit` INT NOT NULL DEFAULT 0,
  `is_online` BOOLEAN NOT NULL DEFAULT FALSE,
  `ranking` INT NOT NULL DEFAULT 1 COMMENT '对话排序',
  `email` VARCHAR(255) NOT NULL COMMENT '邮件',
  `mobile` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手机号',
  `public_email` VARCHAR(255) NOT NULL DEFAULT '',
  `public_telephone` VARCHAR(32) NOT NULL DEFAULT '',
  `qq_num` VARCHAR(50) NOT NULL DEFAULT '',
  `signature` VARCHAR(200) NOT NULL  DEFAULT '',
  `status` VARCHAR(20) NOT NULL  DEFAULT '',
  `wechat` VARCHAR(50) NOT NULL  DEFAULT '',
  `is_admin` TINYINT NOT NULL DEFAULT 0 COMMENT '是否管理员',
  `perms_range_type` VARCHAR(500) NOT NULL COMMENT '权限范围',
  `account_status` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '账号状态',
  `create_at` DATETIME(6) NOT NULL DEFAULT NOW(6) COMMENT '创建时间',
  `update_at` DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6) COMMENT '修改时间',
  `deleted_at` DATETIME(6) DEFAULT NULL COMMENT '删除时间',
  KEY `idx_ent` (`ent_id`),
  KEY `idx_group` (`group_id`),
  KEY `idx_role` (`role_id`),
  UNIQUE KEY (`username`),
  UNIQUE KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `agent_invitation` (
    `id` CHAR(20) PRIMARY KEY,
    `enterprise_id` CHAR(20) NOT NULL,
    `group_id` CHAR(20) NOT NULL,
    `email` VARCHAR(128) NOT NULL,
    `realname` VARCHAR(200) NOT NULL DEFAULT '',
    `serving_limit` INT NOT NULL DEFAULT 0,
    `status` VARCHAR(50) NOT NULL DEFAULT '',
    `work_num` VARCHAR(100) NOT NULL DEFAULT '',
    `privilege` VARCHAR(50) NOT NULL,
    `privilege_range` VARCHAR(200) NOT NULL DEFAULT 'self',
    `created_on` DATETIME(6) NOT NULL DEFAULT NOW(6) COMMENT '创建时间',
    `last_updated` DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6) COMMENT '修改时间',
    `expired_on` DATETIME(6) NOT NULL DEFAULT NOW(6),
    `accepted_on` DATETIME(6) NULL,
    KEY `idx_enterprise` (`enterprise_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;