/*"agent_effective_msg_num": 0,
"agent_id": 9422,
"agent_msg_num": 0,
"agent_type": "human",
"assignee": 9422,
"client_first_send_time": null,
"client_msg_num": 0,
"clues": null,
"converse_duration": 0,
"created_on": "2018-11-04T14:05:13.460164",
"ended_by": null,
"ended_on": null,
"enterprise_id": 5869,
"first_msg_created_on": null,
"first_response_wait_time": null,
"id": 373491096,
"last_msg_content": null,
"last_msg_created_on": null,
"last_updated": "2018-11-04T14:05:13.460175",
"msg_num": 0,
"quality_grade": null,
"title": "\u5728\u7ebf\u54a8\u8be2",
"track_id": "1CWfQ7KiD3GI6PmuqYc0q997u62",
"url": "https://static.meiqia.com/dist/standalone.html?_=t&eid=5869",
"visit_id": "1CWfQ2SJDfjNTFfN8YqHn63fqTU"
*/

CREATE TABLE `conversation` (
  `id` CHAR(20) PRIMARY KEY,
  `ent_id` CHAR(20) NOT NULL,
  `trace_id` CHAR(20) NOT NULL,
  `agent_id` CHAR(20) NOT NULL,
  `agent_msg_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `agent_type` VARCHAR(20) NOT NULL,
  `msg_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `title` VARCHAR(50) NOT NULL DEFAULT '',
  `client_first_send_time` DATETIME(6),
  `client_msg_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `duration` INT UNSIGNED NOT NULL DEFAULT 0,
  `first_msg_created_at` DATETIME(6),
  `first_response_wait_time` INT DEFAULT 0,
  `last_msg_content` VARCHAR(2000) DEFAULT '',
  `last_msg_created_at` DATETIME(6) DEFAULT NULL,
  `quality_grade` VARCHAR(20) DEFAULT '',
  `summary` VARCHAR(500) NOT NULL DEFAULT '',
  `created_at` DATETIME(6) NOT NULL DEFAULT NOW(6),
  `update_at` DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6),
  `ended_at` DATETIME(6),
  `ended_by` CHAR(20),
  `agent_effective_msg_count` INT NOT NULL DEFAULT 0,
  `client_last_send_time` DATETIME(6),
  `first_msg_create_time` DATETIME(6),
  `eval_content` VARCHAR(500) NOT NULL DEFAULT '',
  `eval_level` INT NOT NULL DEFAULT 0,
  `has_summary` BOOLEAN NOT NULL DEFAULT FALSE,
  KEY `idx_ent` (`ent_id`),
  KEY `idx_agent` (`agent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
