CREATE TABLE `enterprise` (
  `id` CHAR(20) PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL COMMENT '企(事)业单位名称',
  `admin_id` CHAR(20) NOT NULL,
  `allocation_rule` VARCHAR(100) NOT NULL DEFAULT '',
  `full_name` VARCHAR(100) NOT NULL DEFAULT '',
  `nick_name` VARCHAR(100) NOT NULL DEFAULT '',
  `province` VARCHAR(100) NOT NULL DEFAULT '',
  `city` VARCHAR(100) NOT NULL DEFAULT '',
  `avatar` VARCHAR(255) NOT NULL DEFAULT '',
  `industry` VARCHAR(255) NOT NULL DEFAULT '',
  `location` VARCHAR(255) NOT NULL DEFAULT '',
  `address` VARCHAR(255) NOT NULL DEFAULT '',
  `website` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(128) NOT NULL COMMENT '电子邮件',
  `mobile` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '联系电话',
  `description` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '描述',
  `created_at` DATETIME(6) NOT NULL DEFAULT NOW(6) COMMENT '创建时间',
  `owner` VARCHAR(255) NOT NULL COMMENT '所属人',
  `plan` INT(11) NOT NULL COMMENT '企业版本',
  `agent_num` INT(11) NOT NULL COMMENT '坐席数',
  `trial_status` INT(11) NOT NULL COMMENT '试用状态',
  `is_activated` BOOLEAN NOT NULL DEFAULT FALSE,
  `expiration_time` DATETIME(6) NOT NULL DEFAULT NOW(6) COMMENT '过期时间',
  `last_activated_at` DATETIME(6) NULL DEFAULT NULL,
  `contact_mobile` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '对外联系方式',
  `contact_email` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '对外联系方式',
  `contact_qq` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '对外联系方式',
  `contact_wechat` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '对外联系方式',
  `contact_signature` VARCHAR(255) NOT NULL DEFAULT '',
  `contact_name` VARCHAR(255) NOT NULL DEFAULT '',
  UNIQUE KEY (`name`),
  UNIQUE KEY (`admin_id`),
  UNIQUE KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

