// Package models contains the types for schema 'custmchat'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"

	"github.com/go-sql-driver/mysql"
)

// InvitationMech represents a row from 'custmchat.invitation_mechs'.
type InvitationMech struct {
	RuleID      string         `json:"rule_id"`      // rule_id
	EntID       string         `json:"ent_id"`       // ent_id
	Name        string         `json:"name"`         // name
	Target      string         `json:"target"`       // target
	BeginAt     time.Time      `json:"begin_at"`     // begin_at
	ExpireAt    mysql.NullTime `json:"expire_at"`    // expire_at
	Enabled     bool           `json:"enabled"`      // enabled
	StyleConfig string         `json:"style_config"` // style_config
	IsAny       bool           `json:"is_any"`       // is_any
	Version     string         `json:"version"`      // version
	CreatedAt   time.Time      `json:"created_at"`   // created_at
	UpdatedAt   time.Time      `json:"updated_at"`   // updated_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the InvitationMech exists in the database.
func (im *InvitationMech) Exists() bool {
	return im._exists
}

// Deleted provides information if the InvitationMech has been deleted from the database.
func (im *InvitationMech) Deleted() bool {
	return im._deleted
}

// Insert inserts the InvitationMech to the database.
func (im *InvitationMech) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if im._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO custmchat.invitation_mechs (` +
		`rule_id, ent_id, name, target, begin_at, expire_at, enabled, style_config, is_any, version, created_at, updated_at` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, im.RuleID, im.EntID, im.Name, im.Target, im.BeginAt, im.ExpireAt, im.Enabled, im.StyleConfig, im.IsAny, im.Version, im.CreatedAt, im.UpdatedAt)
	_, err = db.Exec(sqlstr, im.RuleID, im.EntID, im.Name, im.Target, im.BeginAt, im.ExpireAt, im.Enabled, im.StyleConfig, im.IsAny, im.Version, im.CreatedAt, im.UpdatedAt)
	if err != nil {
		return err
	}

	// set existence
	im._exists = true

	return nil
}

// Update updates the InvitationMech in the database.
func (im *InvitationMech) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !im._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if im._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE custmchat.invitation_mechs SET ` +
		`ent_id = ?, name = ?, target = ?, begin_at = ?, expire_at = ?, enabled = ?, style_config = ?, is_any = ?, version = ?, created_at = ?, updated_at = ?` +
		` WHERE rule_id = ?`

	// run query
	XOLog(sqlstr, im.EntID, im.Name, im.Target, im.BeginAt, im.ExpireAt, im.Enabled, im.StyleConfig, im.IsAny, im.Version, im.CreatedAt, im.UpdatedAt, im.RuleID)
	_, err = db.Exec(sqlstr, im.EntID, im.Name, im.Target, im.BeginAt, im.ExpireAt, im.Enabled, im.StyleConfig, im.IsAny, im.Version, im.CreatedAt, im.UpdatedAt, im.RuleID)
	return err
}

// Save saves the InvitationMech to the database.
func (im *InvitationMech) Save(db XODB) error {
	if im.Exists() {
		return im.Update(db)
	}

	return im.Insert(db)
}

// Delete deletes the InvitationMech from the database.
func (im *InvitationMech) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !im._exists {
		return nil
	}

	// if deleted, bail
	if im._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM custmchat.invitation_mechs WHERE rule_id = ?`

	// run query
	XOLog(sqlstr, im.RuleID)
	_, err = db.Exec(sqlstr, im.RuleID)
	if err != nil {
		return err
	}

	// set deleted
	im._deleted = true

	return nil
}

// InvitationMechesByEntID retrieves a row from 'custmchat.invitation_mechs' as a InvitationMech.
//
// Generated from index 'idx_ent_id'.
func InvitationMechesByEntID(db XODB, entID string) ([]*InvitationMech, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`rule_id, ent_id, name, target, begin_at, expire_at, enabled, style_config, is_any, version, created_at, updated_at ` +
		`FROM custmchat.invitation_mechs ` +
		`WHERE ent_id = ?`

	// run query
	XOLog(sqlstr, entID)
	q, err := db.Query(sqlstr, entID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*InvitationMech{}
	for q.Next() {
		im := InvitationMech{
			_exists: true,
		}

		// scan
		err = q.Scan(&im.RuleID, &im.EntID, &im.Name, &im.Target, &im.BeginAt, &im.ExpireAt, &im.Enabled, &im.StyleConfig, &im.IsAny, &im.Version, &im.CreatedAt, &im.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &im)
	}

	return res, nil
}

// InvitationMechByRuleID retrieves a row from 'custmchat.invitation_mechs' as a InvitationMech.
//
// Generated from index 'invitation_mechs_rule_id_pkey'.
func InvitationMechByRuleID(db XODB, ruleID string) (*InvitationMech, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`rule_id, ent_id, name, target, begin_at, expire_at, enabled, style_config, is_any, version, created_at, updated_at ` +
		`FROM custmchat.invitation_mechs ` +
		`WHERE rule_id = ?`

	// run query
	XOLog(sqlstr, ruleID)
	im := InvitationMech{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, ruleID).Scan(&im.RuleID, &im.EntID, &im.Name, &im.Target, &im.BeginAt, &im.ExpireAt, &im.Enabled, &im.StyleConfig, &im.IsAny, &im.Version, &im.CreatedAt, &im.UpdatedAt)
	if err != nil {
		return nil, err
	}

	return &im, nil
}
