// Package models contains the types for schema 'custmchat'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// VisitorStatistic represents a row from 'custmchat.visitor_statistic'.
type VisitorStatistic struct {
	EntID        string    `json:"ent_id"`        // ent_id
	VisitorCount uint      `json:"visitor_count"` // visitor_count
	VisitNum     uint      `json:"visit_num"`     // visit_num
	PageViews    uint      `json:"page_views"`    // page_views
	CreatedAt    time.Time `json:"created_at"`    // created_at
	UpdatedAt    time.Time `json:"updated_at"`    // updated_at
}

// VisitorStatisticsByEntID retrieves a row from 'custmchat.visitor_statistic' as a VisitorStatistic.
//
// Generated from index 'ent_id'.
func VisitorStatisticsByEntID(db XODB, entID string) ([]*VisitorStatistic, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`ent_id, visitor_count, visit_num, page_views, created_at, updated_at ` +
		`FROM custmchat.visitor_statistic ` +
		`WHERE ent_id = ?`

	// run query
	XOLog(sqlstr, entID)
	q, err := db.Query(sqlstr, entID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*VisitorStatistic{}
	for q.Next() {
		vs := VisitorStatistic{}

		// scan
		err = q.Scan(&vs.EntID, &vs.VisitorCount, &vs.VisitNum, &vs.PageViews, &vs.CreatedAt, &vs.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &vs)
	}

	return res, nil
}
